In [3]:
import pandas as pd

data = pd.read_csv('iphone.csv')

In [26]:
###1 The column names have spaces . rename the column names to have underscore '_' instead of space (try to do in one go instead of specifying each column nam in rename method)
"""data.rename(columns={'Product Name':'Product_Name','Product URL':'Product_URL','Sale Price':'Sale_Price','Number Of Ratings':'Number_Of_Ratings',
                     'Number Of Reviews':'Number_Of_Reviews','Star Rating':'Star_Rating' },inplace='True')"""
data.columns.str.replace(' ','_')
data

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,discount_percentage,space_size,model_name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.544329,2 GB,0.00,NaN,APPLE iPhone 8 Plus
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8 Plus
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8 Plus
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB,24.81,64 GB,APPLE iPhone SE
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB,14.39,NaN,APPLE iPhone 11

In [75]:
data

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [28]:
### 2- start rating for some of the models is missing in the dataset. fill those missing values with the average rating all the models.
avg_star_rating = (data['Star_Rating']).mean(skipna=True)
data.fillna({'Star_Rating':avg_star_rating},inplace=True)   
data   
avg_star_rating

4.57627118644068

In [9]:
### 3- Now instead of filling missing values with avg rating of full dataset , fill with avg rating based on RAM. example :  if rating for a 2 gb phone is missing then take average of all other 2 gb phones rating and fill that value. 

fc = (data['Ram']=='2 GB')
data_2GB = data[fc]
data_2GB_avg = (data_2GB['Star_Rating'].sum()/data_2GB['Star_Rating'].count())
data.loc[fc,'Star_Rating']=data_2GB_avg
data

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.544329,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.544329,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.544329,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.544329,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.544329,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB

In [31]:
### 4- create a new column in the dataframe "Discount_Percentage" based on MRP and sale value
data['discount_percentage'] = round(((data['Mrp']-data['Sale_Price'])/data['Mrp'])*100,2)
data

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,discount_percentage,space_size,model_name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.544329,2 GB,0.00,NaN,APPLE iPhone 8 Plus
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8 Plus
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8 Plus
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.544329,2 GB,0.00,256 GB,APPLE iPhone 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB,24.81,64 GB,APPLE iPhone SE
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB,14.39,64 GB,APPLE iPhone 11
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB,14.39,NaN,APPLE iPhone 11

In [33]:
### 5- which model has highest percent discount ?
sorted_data = data.sort_values(by='Discount_Percentage', ascending=False)
model_with_highest_discount = sorted_data.iloc[0]['Product Name']

KeyError: 'Discount_Percentage'

In [14]:
### - 6.find total no of models  each space configuration (128 GB , 64 GB etc)
split_name = data['Product_Name'].str.split(",")
split_size = split_name.str[1][1:-1]
space_size = split_size.str[1:-1]
data['space_size'] = space_size
data.groupby('space_size')['Product_Name'].count()

space_size
128 GB    24
256 GB    14
512 GB     4
64 GB     18
Name: Product_Name, dtype: int64

In [15]:
###-9 list top 5 models having highest no of reviews 
model_reviews = data.groupby('Product_Name')['Number_Of_Reviews'].sum()
model_reviews_DF = pd.DataFrame({'Models':model_reviews.index,'Reviews':model_reviews.values})
model_reviews_DF.sort_values(by='Reviews',ascending=False,inplace=True)
model_reviews_DF.head(5)

                             Models  Reviews
56  Apple iPhone SE (White, 256 GB)     8161
52    APPLE iPhone SE (Red, 128 GB)     8161
51   APPLE iPhone SE (Black, 64 GB)     8161
50  APPLE iPhone SE (Black, 128 GB)     8161
54   APPLE iPhone SE (White, 64 GB)     8154

In [16]:
#10 - what is the price diffrence between highest price and lowest price iphone (based on mrp)
price_diff = data['Mrp'].max()-data['Mrp'].min()
price_diff

110000

In [23]:
###-11 - find total no of reviews for iphone 11 and iphone 12 category . Output should have only 2 rows (for 11 and 12).
split_name = data['Product_Name'].str.split("(")
data['model_name'] = split_name.str[0]
model_11_12 = data['model_name'=='APPLE iPhone 11' or 'model_name'=='APPLE iPhone 12']
data.groupby('model_name')['Number_Of_Reviews'].count()

KeyError: False

In [166]:
###12- which iphone has 3rd highest MRP
mrp = data.sort_values(by='Mrp', ascending=False)
mrp.head(3).min()

Product_Name                APPLE iPhone 11 Pro (Midnight Green, 512 GB)
Product_URL            https://www.flipkart.com/apple-iphone-11-pro-m...
Brand                                                              Apple
Sale_Price                                                        117900
Mrp                                                               140300
Number_Of_Ratings                                                    542
Number_Of_Reviews                                                     42
Upc                                                     MOBFKCTSSJCWYGCC
Star_Rating                                                          4.5
Ram                                                                 4 GB
discount_percentage                                                  6.0
dtype: object

In [169]:
###-13- what is the average mrp of iphones which costs above 100,000
fc = data['Mrp']>=100000
data[fc]['Mrp'].mean()

130559.09090909091